export const selectUserId = (state) => state.user.userId;
export const selectUserById = (state) => state.user.userById;
export const selectUpdatedUser = (state) => state.user.updatedUser;
export const selectUserList = (state) => state.user.userList;
export const selectSpecialties = (state) => state.user.specialties;
export const selectSpecialtiesFetching = (state) => state.user.specialtiesFetching;
export const selectRoles = (state) => state.user.roles;
export const selectRolesFetching = (state) => state.user.rolesFetching;
export const selectIsFetching = (state) => state.user.isFetching;
