version: '3.9'
services:
  mysqldb:
    image: mysql:latest
    environment:build:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=root
      - MYSQL_PASWORD=admin
      - MYSQL_DATABASE=taskmanager
  expose:
    - "3306"
  ports:
    - "3306:3306"
  volumes:
    - db:/var/lib/taskmanager
  healthcheck:
    test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
    interval: 2s
    timeout: 30s
    retries: 5
  backend:
    build: .
    depends_on:
      - mysqldb
    image: ______________
    environment:
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_FLYWAY_USER=${DB_USERNAME}
      - SPRING_FLYWAY_PASSWORD=${DB_PASSWORD}
    restart: on-failure
    expose:
      - "8080"
    ports:
      - "8080:8080"
  frontend:
    image: ___________________
    ports:
      - "80:3000"
    expose:
      - "3000"
    depends_on:
      - backend
volumes:
  db:



