const LOGIN_START = 'LOGIN_START';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_ERROR = 'LOGIN_ERROR';
const GET_ALL_USERS_START = 'GET_ALL_USERS_START';
const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
const GET_ALL_USERS_ERROR = 'GET_ALL_USERS_ERROR';
const EMAIL = "EMAIL";
const PASSWORD = "PASSWORD";