export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const RECEIVE_USER_AUTH = "RECEIVE_USER_AUTH";
export const RECEIVE_USER_SIGNOUT = "RECEIVE_USER_SIGNOUT";

export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCES";
export const CREATE_TICKET_FAIL = "CREATE_TICKET_FAIL";
export const GET_ALL_TICKETS = "GET_ALL_TICKETS";
