export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const RECEIVE_USER_AUTH = "RECEIVE_USER_AUTH";
export const RECEIVE_USER_SIGNOUT = "RECEIVE_USER_SIGNOUT";

export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCES";
export const CREATE_TICKET_FAIL = "CREATE_TICKET_FAIL";
export const CHANGE_PASSWORD__REQUESTED = "CHANGE_PASSWORD__REQUESTED"
export const GET_ALL_TICKETS = "GET_ALL_TICKETS";

export const CHANGE_TICKET_STATUS = "CHANGE_TICKET_STATUS";
export const SET_TICKET_ID = "SET_TICKET_ID";
export const GET_TICKET_BY_ID = "GET_TICKET_BY_ID";
export const GET_ALL_TICKETS_FOR_KANBAN = "GET_ALL_TICKETS_FOR_KANBAN";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const CLOSE_TICKET = "CLOSE_TICKET";
export const GET_TICKET_LIST = "GET_TICKET_LIST";
export const SELECTED_SPECIALTY = "SELECTED_SPECIALTY";
export const DELETE_TICKET_BY_ID = "DELETE_TICKET_BY_ID";
export const ASSIGN_TICKET_TO_USER = "ASSIGN_TICKET_TO_USER";
export const UPDATE_TICKET_BY_ID = "UPDATE_TICKET_BY_ID";
export const RECEIVE_DUPLICATE_TITLE = "RECEIVE_DUPLICATE_TITLE";
export const GET_STATUSES = "GET_STATUSES";
export const GET_PRIORITIES = "GET_PRIORITIES";
// export const GET_ALL_TICKETS_CREATORS = "GET_ALL_TICKETS_CREATORS";
// export const GET_ALL_TICKETS_DEVELOPERS = "GET_ALL_TICKETS_DEVELOPERS";
export const CHANGE_TICKET_DEVELOPER = "CHANGE_TICKET_DEVELOPER";
