export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const RECEIVE_USER_AUTH = "RECEIVE_USER_AUTH";
export const RECEIVE_USER_SIGNOUT = "RECEIVE_USER_SIGNOUT";

export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCES";
export const CREATE_TICKET_FAIL = "CREATE_TICKET_FAIL";

export const CHANGE_TICKET_STATUS = "CHANGE_TICKET_STATUS";
export const SET_TICKET_ID = "SET_TICKET_ID";
export const GET_TICKET_BY_ID = "GET_TICKET_BY_ID";
export const GET_ALL_TICKETS_FOR_KANBAN = "GET_ALL_TICKETS_FOR_KANBAN";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const GET_TICKET_LIST = "GET_TICKET_LIST";
export const SELECTED_SPECIALTY = "SELECTED_SPECIALTY";
export const DELETE_TICKET_BY_ID = "DELETE_TICKET_BY_ID";
export const UPDATE_TICKET_BY_ID = "UPDATE_TICKET_BY_ID";
export const RECEIVE_DUPLICATE_TITLE = "RECEIVE_DUPLICATE_TITLE";
export const GET_STATUSES = "GET_STATUSES";
export const GET_PRIORITIES = "GET_PRIORITIES";
export const CHANGE_TICKET_DEVELOPER = "CHANGE_TICKET_DEVELOPER";
export const SET_BACKLOG_FIRST_FILTER_VALUE = "SET_BACKLOG_FIRST_FILTER_VALUE";
export const SET_FILTERED_TICKETS = "SET_FILTERED_TICKETS";
export const RESET_FILTERED_TICKETS = "RESET_FILTERED_TICKETS";
export const SEND_COUNTER_TOKEN_TO_BACK = "SEND_COUNTER_TOKEN_TO_BACK";
export const CHECK_TOKEN_VALIDITY = "CHECK_TOKEN_VALIDITY";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const IS_DUPLICATE_TICKET_TITLE = "IS_DUPLICATE_TICKET_TITLE";

