export const routes = {
    BASIC_URL: "http://34.116.152.149:8080/",
    BASIC_PATH: "api/",
    AUTH_URL: "auth/login/",
    LOGOUT_URL: "auth/logout",
    USER_BY_ID: "users/",
    CREATE_USER: "users/",
    TICKET_BY_ID: "tickets/",
    EMAIL_SEND: "/emails/reset-password",
    TICKETS: "tickets/",
    STATUSES: "statuses/",
    PRIORITIES: "priorities/",
    ROLES: "roles",
    SPECIALTIES: "specialties",
    USERS_BY_SPECIALTY: "users/specialty",
    CREATE_TICKET: "tickets/",
    ALL_TICKETS_FOR_KANBAN: "tickets/kanban",
    CHANGE_TICKET_STATUS: "tickets/",
    CHANGE_TICKET_DEVELOPER: "tickets/",
    SET_JWT_TOKEN: "token/",
    CHECK_IF_TICKET_TITLE_EXIST: "tickets/exist-title",
    USERS_BY_ROLE: "users/role"
};
